/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface StencilCounter {
    'name': number;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLStencilCounterElement extends Components.StencilCounter, HTMLStencilElement {}
  var HTMLStencilCounterElement: {
    prototype: HTMLStencilCounterElement;
    new (): HTMLStencilCounterElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'stencil-counter': HTMLStencilCounterElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface StencilCounter extends JSXBase.HTMLAttributes<HTMLStencilCounterElement> {
    'name'?: number;
    'onChange'?: (event: CustomEvent<number>) => void;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'stencil-counter': StencilCounter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


